// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="footer__collections">
      <ul class="footer__collections--list">
        <li
          class="footer__collection"
          :class="{ active: active === 'all' }"
          @mouseover="mouseoverActive('all')"
          @mouseleave="mouseleaveActive('all')"
          @click="setActive('all')">
          <span class="footer__collection--color all"></span>
          All
        </li>
        <li
          class="footer__collection"
          :class="{ active: active === 'essays' }"
          @mouseover="mouseoverActive('essays')"
          @mouseleave="mouseleaveActive('essays')"
          @click="setActive('essays')">
          <span class="footer__collection--color essays"></span>
          Essays
        </li>
        <li
          class="footer__collection"
          :class="{ active: active === 'projects' }"
          @mouseover="mouseoverActive('projects')"
          @mouseleave="mouseleaveActive('projects')"
          @click="setActive('projects')">
          <span class="footer__collection--color projects"></span>
          Projects
        </li>
        <li
          class="footer__collection"
          @mouseover="mouseoverActive('tweetstorms')"
          @mouseleave="mouseleaveActive('tweetstorms')"
          :class="{ active: active === 'tweetstorms' }"
          @click="setActive('tweetstorms')">
          <span class="footer__collection--color tweetstorms"></span>
          Tweetstorms
        </li>
      </ul>
    </div>
    <div class="footer__links">
      <a href="https://aemail.com/vw8" target="_blank" class="footer__link">
        <MailIcon class="footer__link-icon footer__link-icon--email" />
      </a>
      <a href="https://twitter.com/ycparak" target="_blank" class="footer__link">
        <TwitterIcon class="footer__link-icon footer__link-icon--twitter" />
      </a>
      <a href="https://github.com/ycparak" target="_blank" class="footer__link">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true" class="footer__link-icon">
          <title>GitHub icon</title>
          <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12" />
        </svg>
      </a>
    </div>
  </footer>
</template>

<script>
import { MailIcon, TwitterIcon } from 'vue-feather-icons';

export default {
  name: 'Footer',
  components: {
    MailIcon,
    TwitterIcon
  },
  data() {
    return {
      prevActive: 'all',
      active: 'all',
    };
  },
  methods: {
    setActive(collection) {
      this.prevActive = collection;
      this.active = collection;
    },
    mouseoverActive(collection) {
      this.active = collection;
    },
    mouseleaveActive(collection) {
      this.active = this.prevActive;
    }
  },
  watch: {
    active() {
      this.$parent.setPrimaryColor(this.active);
    }
  }
}
</script>

<style lang="scss" scoped>
.footer {
  position: fixed;
  left: 44px;
  bottom: 44px;
  right: 44px;
  display: grid;
  grid-template-columns: 75% 1fr;
  align-items: end;
  color: var(--text-color);
  @include daynight;
  @media (max-width: 1500px) {
    bottom: 32px;
    left: 32px;
    right: 32px;
  }
  @media (max-width: 768px) {
    bottom: 24px;
    left: 24px;
    right: 24px;
  }
  @media (max-width: 676px) {
    bottom: 20px;
    left: 20px;
    right: 20px;
  }
  @media (max-width: 576px) {
    bottom: 12px;
    left: 12px;
    right: 12px;
  }
}
.footer__collections--list {
  display: inline-block;
  margin: 0;
  padding: 0;
  position: relative;
  bottom: -2px;
  .footer__collection {
    font-size: 15px;
    line-height: 15px;
    margin: 0;
    padding: 8px 0;
    color: var(--neutral-color);
    font-weight: 300;
    cursor: pointer;
    &:last-child {
      padding-bottom: 0;
    }
    .footer__collection--color {
      display: inline-block;
      width: 8px;
      height: 8px;
      background: var(--accent-color-2);
      margin-right: 4px;
      border-radius: 50%;
      position: relative;
      top: -1px;
      opacity: 0.1;
      &.essays  {
        background: var(--essays-color);
      }
      &.projects  {
        background: var(--projects-color);
      }
      &.tweetstorms  {
        background: var(--twitter-color);
      }
    }
  }
  .active {
    font-weight: 500;
    color: var(--text-color);
    @include daynight;
    .footer__collection--color{
      opacity: 1;
      @include daynight;
    }
  }
}
.footer__links {
  display: grid;
  text-align: center;
  justify-content: end;
  position: relative;
  right: -7px;
  bottom: -7px;
}
.footer__link {
  display: block;
  margin: 8px 0;
  padding: 0;
  text-decoration: none;
  position: relative;
  top: -4px;
  color: var(--text-color);
  height: 28px;
  width: 28px;
  border-radius: 50%;
  background: transparent;
  &:last-child {
    margin-bottom: 0;
  }
  &:hover, &:focus, &:active {
    outline: none;
    box-shadow: none;
  }
  // Icons
  .footer__link-icon {
    vertical-align: middle;
    fill: var(--text-color);
    width: 15px;
    height: 15px;
    @include daynight;
  }
  .footer__link-icon--email {
    height: 17px;
    width: 17px;
    fill: transparent;
    stroke: var(--text-color)
  }
  .footer__link-icon--twitter {
    width: 16px;
    height: 16px;
    fill: var(--text-color);
    stroke: var(--text-color);
    position: relative;
    top: 1px;
  }
}
.footer__link:hover .footer__link-icon {
  fill: var(--neutral-color);
}
.footer__link:hover .footer__link-icon--email {
  fill: var(--background-color);
  stroke: var(--neutral-color);
}
.footer__link:hover .footer__link-icon--twitter {
  fill: var(--neutral-color);
  stroke: var(--neutral-color);
}
</style>

// src/components/Footer.svelte
<footer>
  <div class="box">
    <div class="box-row">
      <a draggable="false" href="/" class="logo">YP</a>
      <nav>
        <a draggable="false" class="nav-link" href="/">Portfolio</a>
        <a draggable="false" class="nav-link" href="/writing">Writing</a>
        <a draggable="false" class="nav-link" href="/about">About</a>
      </nav>
    </div>
    <div class="box-row">
      <a class="social-link" href="https://github.com/ycparak/ycparak">21 stars</a>
      <nav>
        <a draggable="false" class="social-link" href="mailto:yusuf@ycparak.com">Email</a>
        <a draggable="false" class="social-link" href="https://twitter.com/ycparak">Twitter</a>
        <a draggable="false" class="social-link" href="https://github.com/ycparak/ycparak">Github</a>
      </nav>
    </div>
  </div>
</footer>

<style lang="scss">
  footer {
    position: fixed;
    bottom: functions.toRem(20px);
    left: 0;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    height: fit-content;
    pointer-events: none;
    z-index: 999;
    cursor: default;
  }

  .box {
    position: relative;
    display: block;
    background-color: rgba(245, 245, 245, 0.6);
    border: 1px solid rgb(229, 231, 235);
    backdrop-filter: blur(16px);
    border-radius: functions.toRem(12px);
    width: 360px;
    box-shadow: 0 4px 8px rgba(0,0,0,.12);
    pointer-events: all;

    &-row {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: functions.toRem(10px) functions.toRem(16px);
      width: 100%;
      &:first-child {
        padding: functions.toRem(12px) functions.toRem(16px);
        border-bottom: 1px solid rgb(229, 231, 235);
      }

      nav {
        display: flex;
        align-items: center;
        gap: functions.toRem(8px);
      }

      a {
        text-decoration: none;
        color: inherit;
        user-select: none;
        &:hover, &:focus, &:active {
          text-decoration: none;
        }

        &.logo {
          @include mixins.interface-type-xl;
        }

        &.nav-link {
          @include mixins.interface-type-md;
        }

        &.social-link {
          @include mixins.interface-type-xs;
          opacity: .5;
        }
      }
    }
  }
</style>
